services:
  nginx:
    image: nginx:alpine
    container_name: nginx-yap
    ports:
      - "80:80"
    volumes:
      - ./seve:/var/www
      - ./.infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - laravel_net

  laravel:
    build:
      context: . 
      dockerfile: .Dockerfile
    container_name: server-yap
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - laravel_net

networks:
  laravel_net: